### ISSUE TITLE
Staked/Mined Linda not included in the Linda Balance after migrating wallets

### ISSUE THREAD

**Issue by LucidSplendor** [TheLindaProjectInc/Altitude#16]
Staked/Mined Linda not included in the Linda Balance after migrating wallets. Recently installed Metrix Core v3.3.3.0-g to replace the Linda 2.0 Wallet; now only see my original Linda deposit. Can you please help me to fix this? I know it's not much but it is still Linda that was earned and deserved. Thanks for your consideration.

 **LSqY8VynurTtfSZ3vy5ww7wMepjGHXixX3**

![Linda_01](https://user-images.githubusercontent.com/52475884/60557293-d7092000-9cf9-11e9-8446-f5811d5d7f43.JPG)

![Linda_03](https://user-images.githubusercontent.com/52475884/60557307-eb4d1d00-9cf9-11e9-8f45-0b6507d87751.JPG)

**Comment by davidstoneham** [comment]
Hi @LucidSplendor unfortunately you were operating on a side chain and not the main chain. The Linda you mined disappeared once you rejoined the main chain. We have made some protocol updates since wallet 2.0 to ensure the safety and fairness of our chain for all users. I understand it must be frustrating to open your wallet and see coins missing but that is why it's important to keep up to date.

You can check our website, twitter or discord for updates and important information in the future.

**Comment by LucidSplendor** [comment]
Do not close this case until we are finished entirely. I refuse to accept
that explanation due to the fact that all I did was install your wallet...
Linda 2.0 and then sit on the Linda coins. If it was on some side chain,
that should be YOUR problem, not mine. I never made any changes.

**Comment by LucidSplendor** [comment]
THIS CASE IS NOT CLOSED!

**Comment by davidstoneham** [comment]
Again I understand the frustration but you did not keep your software up to date during a protocol fork. There is nothing that we can do for you to give coins you mined on a side chain. You are welcome to return to using the 2.0 wallet and your mined coins will still be there. However, they are not recognized by us, any of our platforms, partners or exchanges as real coins so you will not be able to use them.
I'm sure you can understand that we must make protocol changes to ensure the safety of our chain and users. The 2.0 fork was due to a rouge miner exploiting a bug and allowing them to mine and dump a massive amount of coins. 
I wish we there was something we could do but I am just explaining to you why those coins have suddenly disappeared.

**Comment by LucidSplendor** [comment]
Look, you understand that these were deposited to the same account as my original balance? - this just sounds like another way to rip people off. If there were no changes to the wallet, there's nothing that would say that I was on some side chain cheating the developers somehow.

**Comment by LucidSplendor** [comment]
I can understand the rouge miner thing - sorry, yes it's very frustrating. I'll just suck it up, getting used to being ripped off from many sh*t-coins...I can't catch a break!
Thanks for the explanation.

**Comment by davidstoneham** [comment]
If we hadn't have changed the wallet then a rouge miner would have mined and dumped all 30 billion Metrix by now and the chain would be dead, losing thousands of people's investments.
We do not gain financially from protocol forks and I personally only implement them if it is absolutely necessary as I understand there will be some people who are not aware of the changes and fail to update in time, causing this exact issue.

You can deposit coins into the same address on different chains and those coins will not exist when you move to a different chain even though they were sent to the same address.
You can check your wallet balance on an explorer and you'll see they simply are not there.
