### ISSUE TITLE
EXCEPTION: St13runtime_error, tinyformat: Not enough conversion specifiers in format string

### ISSUE THREAD

**Issue by cryptocoinguru** [TheLindaProjectInc/Altitude#18]
I'm getting exception while my wallet is unable to completly sync blockchain:

```
ProcessMessage(tx, 376 bytes) FAILED
************************
EXCEPTION: St13runtime_error       
tinyformat: Not enough conversion specifiers in format string       
Metrix in ProcessMessages()
```

Bitcoin-Core seems to have similar issue already resolved, please see:
https://github.com/bitcoin/bitcoin/issues/9423

**Comment by davidstoneham** [comment]
This is an issue with the Metrix Core and will be addressed in the next release. This error is due to one of the many debug logs missing a variable. It should not affect the syncing of the node however as it's purpose is to just log some information about the received message.

Make sure you are running the latest version Metrix Core and try a re-index from Altitude. If you're still having issues please head to our [discord](https://discordapp.com/invite/5nwrTwJ) so we can grab your debug.log and see what exactly your syncing issue is.

**Comment by davidstoneham** [comment]
This issue has been resolved in the latest Metrix core version
