### ISSUE TITLE
Restore my Altitude Metrix Wallet

### ISSUE THREAD

**Issue by AndiNBG** [TheLindaProjectInc/Altitude#20]
Description of issue: Please describe the issue with as much information as possible

Machine: x64 win32
Altitude: 2.1.5
Metrix Core: v3.4.6.0-g
Connections: 23
Blocks: 69368
Log: https://file.io/FyNB0m
Hello.I want to restore my Metrix Wallet. The passphrase I have, how does it work?

**Comment by davidstoneham** [comment]
Your blockchain isn't completely synced. If you're having an issue with your wallet balance you will need to wait for the blockchain to sync completely.

Your passphrase is used to encrypt your wallet file so that is is secure. Make sure you do not lose your wallet passphrase or you won't be able to access your funds.

If you require further assistance please head over to our discord https://discord.gg/5nwrTwJ
